#version=7.0.8-SNAPSHOT
version=7.0.7

org.gradle.caching=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true

kotlinVersion=2.2.21
byteBuddyVersion=1.17.6

kotlin.jvm.target.validation.mode=ignore
kotlin.stdlib.default.dependency=false

-------------------------------\u672C\u5730\u4EE3\u7406-------------------------------
# \u5C06\u6D41\u91CF\u8F6C\u53D1\u5230\u672C\u673A ClashX
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
# \u672C\u5730\u5730\u5740\u7684\u6D41\u91CF\u4E0D\u8F6C\u53D1
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1
